version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:  |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
     - run: |
            docker build -t $DOCKER_HUB_USER/launchboat .
     - run: |
            docker run $DOCKER_HUB_USER/launchboat
     - deploy:
           name: push to docker hub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker push $DOCKER_ID_USER/launchboat
              fi

