version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Container
           command: |
            docker build -t $DOCKER_HUB_USER/launchboat .
     - run:
           name: Test Container
           command: |
            OUTFILE=`docker run $DOCKER_HUB_USER/launchboat pkgtest.R https://github.com/ropensci/plater`
            wget $OUTFILE -O test-report.html
     - store_artifacts:
          path: test-report.html
     - deploy:
           name: Push to Docker Hub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push $DOCKER_HUB_USER/launchboat
              fi

workflows:
   version: 2
   commit:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build


