version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Container
           command: |
            docker build -t $DOCKER_HUB_USER/launchboat .
     - run:
           name: Test Container
           command: |
            docker run -v "$(pwd):/home/rstudio/pkg" $DOCKER_HUB_USER/launchboat https://github.com/ropensci/plater
     - store_artifacts:
          path: /root/main/ro-check/
          destination: artifacts
     - deploy:
           name: Push to Docker Hub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push $DOCKER_HUB_USER/launchboat
              fi

workflows:
   version: 2
   main:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build


